// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFxSRULyNEpCuk4HdytVoQLsNUm0HtRIM',
    appId: '1:156433260912:web:040a53bd6c4ab9cbb8efb5',
    messagingSenderId: '156433260912',
    projectId: 'dream-app-if22dev',
    authDomain: 'dream-app-if22dev.firebaseapp.com',
    storageBucket: 'dream-app-if22dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCENt-_7trhIT0wgNYrszK5GTPCX-dhz4',
    appId: '1:156433260912:android:96f3ba17479eb34db8efb5',
    messagingSenderId: '156433260912',
    projectId: 'dream-app-if22dev',
    storageBucket: 'dream-app-if22dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfwEXass7S5JfFe2kg2wobH5ShVfOsxpI',
    appId: '1:156433260912:ios:f40bae12b7f29f01b8efb5',
    messagingSenderId: '156433260912',
    projectId: 'dream-app-if22dev',
    storageBucket: 'dream-app-if22dev.firebasestorage.app',
    iosBundleId: 'com.example.dreamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfwEXass7S5JfFe2kg2wobH5ShVfOsxpI',
    appId: '1:156433260912:ios:f40bae12b7f29f01b8efb5',
    messagingSenderId: '156433260912',
    projectId: 'dream-app-if22dev',
    storageBucket: 'dream-app-if22dev.firebasestorage.app',
    iosBundleId: 'com.example.dreamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFxSRULyNEpCuk4HdytVoQLsNUm0HtRIM',
    appId: '1:156433260912:web:9d100cb3901340f8b8efb5',
    messagingSenderId: '156433260912',
    projectId: 'dream-app-if22dev',
    authDomain: 'dream-app-if22dev.firebaseapp.com',
    storageBucket: 'dream-app-if22dev.firebasestorage.app',
  );
}
